services:
  spark-master:
    image: spark-image 
    container_name: spark-master
    entrypoint: ['./entrypoint.sh', 'master']
    build:
      context: ./containers/spark
      dockerfile: Dockerfile.Spark 
    ports:
      - "4040:4040"
      - "9090:8080"
      - "7077:7077"
      - "3000:3000"
    volumes:
      - ../scripts/spark:/opt/spark/work-dir/scripts
      - ./containers/spark/spark-logs:/opt/spark/spark-events
    env_file:
      - .env.spark
  
  spark-history-server:
    container_name: spark-history
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - ./containers/spark/spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'
  
  spark-worker:
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'worker']
    volumes:
      - ../scripts/spark:/opt/spark/work-dir/scripts
      - ./containers/spark/spark-logs:/opt/spark/spark-events
    env_file:
      - .env.spark
 
  minio:
    image: 'minio/minio:latest'
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'  
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data
